[
  {
    id: 1,
    name: "Responsible AI and Human Centred Technology",
    tagline: "Human-centered and responsible AI for all",
    skills: ["python", "javascript", "Technical writing"],
    topicTags: ["machine learning", "ai", "Fairness", "Robustness", "Safety"],
    ideasLink:
      "https://docs.google.com/document/d/1_PinY76lVHWAfahBmrvK5MKugXxZm6LZ03I-vfDWri0/edit#",
    websiteLink: "https://www.tensorflow.org/responsible_ai",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 2,
    name: "CircuitVerse.org",
    tagline: "Build and learn logic circuits in the cloud!",
    skills: ["javascript", "rails", "canvas"],
    topicTags: [
      "education",
      "web",
      "simulation",
      "pedagogy",
      "digital logic design",
    ],
    ideasLink:
      "https://github.com/CircuitVerse/CircuitVerse/wiki/GSoC%2722-Project-List",
    websiteLink: "http://circuitverse.org/",
    categories: ["Science and medicine", "End user applications"],
  },

  {
    id: 3,
    name: "Forschungszentrum Jülich",
    tagline: "Shaping change: open source for Big Science",
    skills: ["python", "mpi", "high performance computing", "pytorch", "gpu"],
    topicTags: [
      "neuroscience",
      "data analytics",
      "astrophysics",
      "data-intensive science",
      "earth-system monitoring",
    ],
    ideasLink:
      "https://docs.google.com/document/d/1OKUf_n_whN0M20c__jj8R5jyGABPYYxmdBfyzto4OZk",
    websiteLink: "https://fz-juelich.de/en",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 4,
    name: "52°North Spatial Information Research GmbH",
    tagline: "Innovative ideas & technologies in geoinformatics",
    skills: ["javascript", "android", "java", "web services", "ogc standards"],
    topicTags: [
      "citizen science",
      "spatial information infrastructures",
      "open standards",
      "data analytics",
      "Geoinformation",
    ],
    ideasLink: "https://wiki.52north.org/Projects/GSoC2022ProjectIdeas",
    websiteLink: "https://52north.org/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 5,
    name: "RTEMS Project",
    tagline: "A real-time operating system for Earth & Space",
    skills: ["python", "c/c++", "assembly", "posix"],
    topicTags: ["kernel", "embedded", "real-time", "multicore", "rtos"],
    ideasLink: "https://devel.rtems.org/wiki/Developer/OpenProjects",
    websiteLink: "https://www.rtems.org/",
    categories: ["Operating systems", "Science and medicine"],
  },

  {
    id: 6,
    name: "sktime",
    tagline: "A unified framework for ML with time series",
    skills: ["python", "github", "sphinx", "scikit-learn"],
    topicTags: ["data science", "ai", "time series", "toolbox frameworks"],
    ideasLink:
      "https://github.com/sktime/mentoring/blob/main/internships/projects_2022.md",
    websiteLink: "https://www.sktime.org/en/stable/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 7,
    name: "Machine Learning for Science (ML4SCI)",
    tagline: "Machine learning applications in science",
    skills: [
      "python",
      "machine learning",
      "c++",
      "data analysis",
      "artificial intelligence",
    ],
    topicTags: [
      "machine learning",
      "science and medicine",
      "algorithms",
      "physics",
      "astronomy",
    ],
    ideasLink: "https://ml4sci.org/gsoc/2022/summary.html",
    websiteLink: "https://ml4sci.org/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 8,
    name: "National Resource for Network Biology (NRNB)",
    tagline: "Developing open source tools for network biology",
    skills: ["python", "javascript", "java", "xml", "r"],
    topicTags: [
      "web application",
      "data science",
      "graphics",
      "scientific computing",
      "network biology",
    ],
    ideasLink: "https://github.com/nrnb/GoogleSummerOfCode/issues",
    websiteLink: "https://nrnb.org/gsoc.html",
    categories: ["Science and medicine"],
  },

  {
    id: 9,
    name: "Open Genome Informatics",
    tagline: "Open access genomics and bioinformatics projects",
    skills: ["python", "mysql", "react", "r-project", "graph"],
    topicTags: [
      "genomics",
      "bioinformatics",
      "cloud",
      "biology",
      "data discovery",
    ],
    ideasLink: "http://gmod.org/wiki/GSOC_Project_Ideas_2022",
    websiteLink: "http://gmod.org/wiki/GSoC",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 10,
    name: "Open Chemistry",
    tagline: "Advancing Open Source & Open Science for Chemistry",
    skills: ["python", "javascript", "opengl", "c++", "c++14"],
    topicTags: [
      "data science",
      "graphics",
      "scientific visualization",
      "cheminformatics",
      "quantum chemistry",
    ],
    ideasLink: "https://wiki.openchemistry.org/GSoC_Ideas_2022",
    websiteLink: "https://openchemistry.org/",
    categories: ["Science and medicine", "End user applications"],
  },

  {
    id: 11,
    name: "Genome Assembly and Annotation",
    tagline: "Providing freely accessible genomic data",
    skills: ["python", "mysql", "docker", "pytorch", "nextflow"],
    topicTags: ["machine learning", "genomics", "big data", "cloud", "hpc"],
    ideasLink: "https://www.ensembl.info/about/projects/",
    websiteLink: "https://www.ebi.ac.uk/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 12,
    name: "NumFOCUS",
    tagline: "NumFOCUS promotes open source scientific software.",
    skills: ["python", "c++", "r", "julia"],
    topicTags: [
      "data science",
      "graphics",
      "scientific computing",
      "numerical computation",
    ],
    ideasLink:
      "https://github.com/numfocus/gsoc/blob/master/2022/ideas-list.md#ideas-pages",
    websiteLink: "https://numfocus.org",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 13,
    name: "LibreCube Initiative",
    tagline: "Open Source Space and Earth Exploration",
    skills: ["python", "mongodb", "rest", "micropython", "zmq"],
    topicTags: [
      "space",
      "cubesat",
      "mission control",
      "Communication Protocols",
    ],
    ideasLink: "https://librecube.org/google-summer-of-code-2022/",
    websiteLink: "https://librecube.org",
    categories: ["Science and medicine"],
  },

  {
    id: 14,
    name: "SageMath",
    tagline: "Open-source mathematics software system",
    skills: ["python", "cython"],
    topicTags: ["mathematics", "education", "research"],
    ideasLink: "https://wiki.sagemath.org/GSoC/2022",
    websiteLink: "https://www.sagemath.org",
    categories: ["Science and medicine"],
  },

  {
    id: 15,
    name: "Wellcome Sanger Institute",
    tagline: "Genome analysis across the whole tree of life",
    skills: ["python", "javascript", "rust", "nextflow"],
    topicTags: [
      "genomics",
      "bioinformatics",
      "data analysis",
      "genome assembly",
    ],
    ideasLink:
      "https://docs.google.com/document/d/1DAuERVZUaqHyRxcqdk7P8B7HhS7e2EEGfGEx6O7C5ms/edit?usp=sharing",
    websiteLink: "https://www.sanger.ac.uk/programme/tree-of-life/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 16,
    name: "Our World In Data",
    tagline: "Explaining the world's biggest problems with data",
    skills: ["python", "mysql", "d3", "typescript", "pandas"],
    topicTags: ["open data", "data visualisation", "Data cataloging"],
    ideasLink:
      "https://docs.google.com/document/d/1jOKvEfvTSwGxCYZlh5Xfm4uq2jhXqc8JbUXe-QTnHxk/edit?usp=sharing",
    websiteLink: "https://ourworldindata.org/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 17,
    name: "MDAnalysis",
    tagline: "Analysis of molecular simulations data with Python",
    skills: ["python", "cython", "c/c++"],
    topicTags: [
      "science",
      "computational-chemistry",
      "high-performance-computing",
      "molecular-simulation",
      "soft-matter-physics",
    ],
    ideasLink:
      "https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-2022-Project-Ideas",
    websiteLink: "https://www.mdanalysis.org",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 18,
    name: "GNSS-SDR",
    tagline: "An open source GNSS software-defined receiver",
    skills: ["c", "c++", "sdr"],
    topicTags: [
      "gnss",
      "geolocation",
      "navigation",
      "software defined radio",
      "communications",
    ],
    ideasLink: "https://gnss-sdr.org/google-summer-code-2022-ideas-list/",
    websiteLink: "https://gnss-sdr.org/",
    categories: ["Science and medicine", "Other"],
  },

  {
    id: 19,
    name: "GNU Radio",
    tagline: "The free & open software radio ecosystem",
    skills: ["python", "c++", "qt", "simd"],
    topicTags: [
      "real-time",
      "dsp",
      "communications engineering",
      "cybersecurity",
      "Software-Defined Radio",
    ],
    ideasLink: "https://wiki.gnuradio.org/index.php/GSoCIdeas",
    websiteLink: "https://www.gnuradio.org",
    categories: ["Science and medicine"],
  },

  {
    id: 20,
    name: "Internet Health Report",
    tagline: "Monitoring the Internet",
    skills: ["python", "javascript", "apache kafka", "VueJS"],
    topicTags: [
      "networking",
      "routing",
      "communication",
      "internet",
      "data analytics",
    ],
    ideasLink:
      "https://github.com/InternetHealthReport/gsoc/blob/main/ideas.md",
    websiteLink: "https://ihr.iijlab.net",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 21,
    name: "BeagleBoard.org",
    tagline: "Open hardware computing for educators and makers",
    skills: ["linux", "fpga", "risc-v", "dsp", "Zephyr RTOS"],
    topicTags: [
      "robotics",
      "iot",
      "ai",
      "software defined radio",
      "Personal Server",
    ],
    ideasLink: "https://bbb.io/gsocideas",
    websiteLink: "https://beagleboard.org",
    categories: ["Science and medicine", "Infrastructure and cloud"],
  },

  {
    id: 22,
    name: "Semi Technologies",
    tagline: "The ML-first vector search engine",
    skills: [
      "python",
      "machine learning",
      "golang",
      "vectors",
      "natural language processing",
    ],
    topicTags: ["machine learning", "Vector Database", "Search Engines"],
    ideasLink: "https://weaviate.io/resources/gsoc.html",
    websiteLink: "https://weaviate.io",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 23,
    name: "Ste||ar group",
    tagline: "Shaping a Scalable Future",
    skills: ["c++", "hpc"],
    topicTags: [
      "library",
      "optimization",
      "parallel algorithms",
      "hpx",
      "application",
    ],
    ideasLink:
      "https://github.com/STEllAR-GROUP/hpx/wiki/Google-Summer-of-Code-%28GSoC%29-2022",
    websiteLink: "http://stellar-group.org/",
    categories: ["Science and medicine", "Programming languages"],
  },

  {
    id: 24,
    name: "GeomScale",
    tagline: "Scalable geometric and statistical software",
    skills: ["python", "c++", "r", "jupyter", "github-actions"],
    topicTags: [
      "mathematics",
      "data science",
      "computational biology",
      "computational geometry",
      "statistics",
    ],
    ideasLink:
      "https://github.com/GeomScale/gsoc2022/wiki/table-of-proposed-coding-projects",
    websiteLink: "https://geomscale.github.io",
    categories: ["Science and medicine"],
  },

  {
    id: 25,
    name: "OpenAstronomy",
    tagline: "Look at the Universe with the power of open source",
    skills: ["python", "javascript", "julia", "css"],
    topicTags: ["astronomy", "solar physics", "high energy astrophysics"],
    ideasLink: "https://openastronomy.org/gsoc/gsoc2022/#/projects",
    websiteLink: "https://openastronomy.org/",
    categories: ["Science and medicine"],
  },

  {
    id: 26,
    name: "ArduPilot",
    tagline: "World's most advanced autonomous vehicle software",
    skills: ["python", "lua", "c++", "pixhawk"],
    topicTags: [
      "robotics",
      "Drone",
      "autonomous vehicle",
      "UGV",
      "unmanned vehicle",
    ],
    ideasLink: "https://ardupilot.org/dev/docs/gsoc-ideas-list.html",
    websiteLink: "https://ardupilot.org/",
    categories: ["Science and medicine", "End user applications"],
  },

  {
    id: 27,
    name: "PEcAn Project",
    tagline: "Develop and promote tools for ecosystem modeling",
    skills: ["r", "docker", "api", "geospatial"],
    topicTags: [
      "data science",
      "ecosystem models",
      "scientific visualization",
      "climate science",
      "Ecological Forecasting,",
    ],
    ideasLink: "https://pecanproject.github.io/gsoc_ideas.html",
    websiteLink: "https://pecanproject.github.io/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 28,
    name: "TARDIS RT Collaboration",
    tagline: "Exploring supernovae made easy",
    skills: ["python", "numba", "numpy", "jupyter", "pandas"],
    topicTags: ["visualization", "big data", "simulation", "astrophysics"],
    ideasLink: "https://tardis-sn.github.io/gsoc/category/ideas-page.html",
    websiteLink: "https://tardis-sn.github.io",
    categories: ["Science and medicine"],
  },

  {
    id: 29,
    name: "R project for statistical computing",
    tagline: "R software for statistical computing & graphics",
    skills: ["c", "javascript", "c++", "r-project", "fortran"],
    topicTags: [
      "visualization",
      "machine learning",
      "data science",
      "graphics",
      "statistics",
    ],
    ideasLink:
      "https://github.com/rstats-gsoc/gsoc2022/wiki/table%20of%20proposed%20coding%20projects",
    websiteLink: "https://www.r-project.org/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 30,
    name: "Center for Research in Open Source Software (CROSS)",
    tagline: "Amplifying Research Imapct through Open Source",
    skills: ["python", "c/c++", "verilog", "apache arrow", "matlab/simulink"],
    topicTags: [
      "hardware",
      "data science",
      "networking",
      "data management",
      "systems",
    ],
    ideasLink: "https://uccross.github.io/projects",
    websiteLink: "https://cross.ucsc.edu/",
    categories: ["Science and medicine", "Other"],
  },

  {
    id: 31,
    name: "The Julia Language",
    tagline: "A fresh approach to technical computing",
    skills: ["julia"],
    topicTags: [
      "math",
      "machine learning",
      "science",
      "data science",
      "life sciences",
    ],
    ideasLink: "https://julialang.org/jsoc/projects/",
    websiteLink: "https://julialang.org",
    categories: ["Science and medicine", "Programming languages"],
  },

  {
    id: 32,
    name: "MZmine",
    tagline: "Open-source software for mass spectrometry",
    skills: ["java", "javafx"],
    topicTags: [
      "visualization",
      "mass spectrometry",
      "biochemistry",
      "feature detection",
      "ion mobility",
    ],
    ideasLink: "https://mzmine.github.io/gsoc2022.html",
    websiteLink: "https://www.mzmine.org",
    categories: ["Science and medicine"],
  },

  {
    id: 33,
    name: "INCF",
    tagline: "An open & FAIR neuroscience standards organization",
    skills: ["python", "javascript", "java", "c++", "gpu"],
    topicTags: [
      "machine learning",
      "data visualization",
      "neuroscience",
      "brain modelling",
      "neuroimage processing",
    ],
    ideasLink:
      "https://docs.google.com/document/d/131tHl3Ao3aJ_KbfOdZbeDog3sovhHhx_5fobchcpc4Q",
    websiteLink: "https://www.incf.org",
    categories: ["Science and medicine"],
  },

  {
    id: 34,
    name: "mlpack",
    tagline: "mlpack - a fast, flexible machine learning library",
    skills: ["c++", "C++ template metaprogramming"],
    topicTags: [
      "machine learning",
      "embedded",
      "ai",
      "deep learning",
      "Neural networks",
    ],
    ideasLink: "https://github.com/mlpack/mlpack/wiki/SummerOfCodeIdeas",
    websiteLink: "https://www.mlpack.org",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 35,
    name: "TensorFlow",
    tagline: "TensorFlow is a ML framework for everyone.",
    skills: ["machine learning", "tensorflow", "ai", "Jax", "keras"],
    topicTags: ["education", "research", "machine learning"],
    ideasLink:
      "https://docs.google.com/document/d/1fLDLwIhnwDUz3uUV8RyUZiOlmTN9Uzy5ZuvI8iDDFf8/edit#",
    websiteLink: "https://tensorflow.org",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 36,
    name: "SymPy",
    tagline: "SymPy is a Python library for symbolic mathematics",
    skills: ["python", "numpy", "jupyter"],
    topicTags: ["mathematics", "physics", "symbolic mathematics"],
    ideasLink: "https://github.com/sympy/sympy/wiki/GSoC-Ideas",
    websiteLink: "https://www.sympy.org/",
    categories: ["Science and medicine"],
  },

  {
    id: 37,
    name: "Orcasound",
    tagline: "Humans & AI listening together to save the whales.",
    skills: ["python", "javascript", "raspberry pi", "elixir", "NextJs"],
    topicTags: ["web", "audio", "ai", "acoustics", "community science"],
    ideasLink: "https://github.com/orgs/orcasound/projects/2",
    websiteLink: "https://orcasound.net",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 38,
    name: "CGAL Project",
    tagline: "C++ library of computational geometry",
    skills: ["c++", "qt"],
    topicTags: [
      "geometry",
      "mesh processing",
      "computation geometry",
      "geometry processing",
    ],
    ideasLink: "https://github.com/CGAL/cgal/wiki/Project-Ideas",
    websiteLink: "https://www.cgal.org",
    categories: ["Science and medicine"],
  },

  {
    id: 39,
    name: "RADAR-base",
    tagline: "Improve people's quality of life using patient generated data",
    skills: ["java", "kotlin", "docker", "angular", "kafka"],
    topicTags: [
      "web",
      "mhealth",
      "remote patient monitoring",
      "micro-services",
      "devices",
    ],
    ideasLink: "https://github.com/RADAR-base/GSoC",
    websiteLink: "https://radar-base.org/",
    categories: ["Science and medicine"],
  },

  {
    id: 40,
    name: "Center for Translational Data Science",
    tagline: "Develop translational data science.",
    skills: ["python", "aws"],
    topicTags: ["bioinformatics", "data science", "cloud", "Data Meshes"],
    ideasLink:
      "https://docs.google.com/document/d/1BErI5751jBlyyAii4HuL2s7C1McNs78GyWzVZE0RTVw/edit?usp=sharing",
    websiteLink: "https://ctds.uchicago.edu",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 41,
    name: "Cuneiform Digital Library Initiative (CDLI)",
    tagline: "Curating humanity's oldest written sources",
    skills: ["mysql", "javascript", "docker", "php", "SCSS"],
    topicTags: ["linguistics", "History", "culture"],
    ideasLink:
      "https://gitlab.com/cdli/framework/-/wikis/Google-Summer-of-Code-GSoC-2022-Cuneiform-Digital-Library-Initiative-(CDLI)-ideas-list",
    websiteLink: "https://cdli.ucla.edu",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 42,
    name: "IOOS",
    tagline: "Our eyes on the ocean, coasts, and Great Lakes",
    skills: ["python", "ocean science"],
    topicTags: ["open data", "data science"],
    ideasLink: "https://github.com/ioos/gsoc/blob/main/2022/ideas-list.md",
    websiteLink: "https://ioos.noaa.gov/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 43,
    name: "JabRef e.V.",
    tagline: "Open Source bibliography manager",
    skills: ["java", "javafx", "bibtex"],
    topicTags: ["science", "library", "literature"],
    ideasLink: "https://www.jabref.org/GSoC2022.html",
    websiteLink: "https://www.jabref.org/",
    categories: ["Science and medicine", "End user applications"],
  },

  {
    id: 44,
    name: "Public Lab",
    tagline: "Tools for communities to measure pollution",
    skills: ["javascript", "ruby on rails"],
    topicTags: [
      "science",
      "environment",
      "community",
      "documentation",
      "forum",
    ],
    ideasLink: "https://publiclab.org/wiki/gsoc-ideas#2022+Ideas",
    websiteLink: "https://publiclab.org",
    categories: ["Science and medicine", "Social and communication"],
  },

  {
    id: 45,
    name: "Department of Biomedical Informatics, Emory University",
    tagline: "Biomedical research to advance healthcare",
    skills: ["python", "javascript", "java", "workflows", "dicom"],
    topicTags: [
      "science and medicine",
      "data integration",
      "workflows",
      "radiology",
      "distributed system",
    ],
    ideasLink: "https://github.com/NISYSLAB/Emory-BMI-GSoC",
    websiteLink: "https://med.emory.edu/departments/biomedical-informatics/",
    categories: ["Science and medicine"],
  },

  {
    id: 46,
    name: "Open Bioinformatics Foundation (OBF)",
    tagline: "Promote OSS & Open Science in biological research.",
    skills: ["python", "javascript", "c++", "html/css", "Git/GitHub"],
    topicTags: [
      "open science",
      "genomics",
      "bioinformatics",
      "workflows",
      "Open Source Bioinformatics",
    ],
    ideasLink: "https://www.open-bio.org/events/gsoc/gsoc-project-ideas/",
    websiteLink: "https://www.open-bio.org",
    categories: ["Science and medicine"],
  },

  {
    id: 47,
    name: "DBpedia",
    tagline: "Global and Unified Access to Knowledge Graphs.",
    skills: ["python", "javascript", "java", "scala", "rdf"],
    topicTags: [
      "natural language processing",
      "semantic web",
      "linked data",
      "knowledge graph",
      "data extraction",
    ],
    ideasLink: "https://forum.dbpedia.org/tag/gsoc2022-ideas",
    websiteLink: "https://www.dbpedia.org/",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 48,
    name: "LibreHealth",
    tagline: "Healthcare for Humanity",
    skills: ["python", "javascript", "android", "java", "dart/flutter"],
    topicTags: ["web", "deep learning", "hfoss", "radiology", "mobile apps"],
    ideasLink: "https://forums.librehealth.io/ideas",
    websiteLink: "https://librehealth.io",
    categories: ["Science and medicine", "Data"],
  },

  {
    id: 49,
    name: "Global Alliance for Genomics and Health",
    tagline: "We develop genomics tools to benefit human health",
    skills: ["python", "postgresql", "java", "react", "rust"],
    topicTags: ["web", "genomics", "bioinformatics", "genetics", "standards"],
    ideasLink:
      "https://docs.google.com/document/d/1idXkztr7HoH8Zo1YhkW7IZyS74uWY-EmCGJYqf9W3J4",
    websiteLink: "https://ga4gh.org",
    categories: ["Science and medicine", "Web"],
  },

  {
    id: 50,
    name: "Apertus Association",
    tagline: "open source cinema",
    skills: ["python", "c/c++", "fpga", "rust", "nix"],
    topicTags: [
      "computer vision",
      "linux",
      "camera",
      "image processing",
      "digital hardware design",
    ],
    ideasLink: "https://lab.apertus.org/project/view/20/",
    websiteLink: "https://www.apertus.org/",
    categories: ["Science and medicine", "Media"],
  },

  {
    id: 51,
    name: "CERN-HSF",
    tagline: "Umbrella for Particle Physics-related projects",
    skills: [
      "python",
      "c/c++",
      "data analysis",
      "artificial intelligence",
      "container orchestration",
    ],
    topicTags: [
      "machine learning",
      "big data",
      "algorithmics",
      "particle physics",
      "Performance Optimisation",
    ],
    ideasLink: "https://hepsoftwarefoundation.org/activities/gsoc.html",
    websiteLink: "http://hepsoftwarefoundation.org/activities/gsoc.html",
    categories: ["Science and medicine"],
  },

  {
    id: 52,
    name: "MBDyn",
    tagline: "Open Source Multibody Simulation",
    skills: ["python", "c++"],
    topicTags: [
      "robotics",
      "scientific computing",
      "multibody dynamics",
      "aeroelasticity",
      "Structural engineering",
    ],
    ideasLink:
      "https://public.gitlab.polimi.it/DAER/mbdyn/-/wikis/Google-Summer-of-Code/GSoC-Project-Ideas",
    websiteLink: "http://www.mbdyn.org/",
    categories: ["Science and medicine"],
  },

  {
    id: 53,
    name: "MoveIt",
    tagline: "Moving robots into the future",
    skills: ["ros", "c++"],
    topicTags: [
      "robotics",
      "motion planning",
      "trajectory generation",
      "kinematics",
    ],
    ideasLink: "https://moveit.ros.org/events/2022-google-summer-of-code/",
    websiteLink: "https://moveit.ros.org",
    categories: ["Science and medicine", "Other"],
  },

  {
    id: 54,
    name: "Open Food Facts",
    tagline: "Better food choices for your health & the planet",
    skills: ["python", "machine learning", "perl", "tensorflow", "flutter"],
    topicTags: ["open data", "health", "environment", "mobile", "food"],
    ideasLink: "https://world.openfoodfacts.org/google-summer-of-code",
    websiteLink: "https://world.openfoodfacts.org/discover",
    categories: ["Science and medicine", "End user applications"],
  },

  {
    id: 55,
    name: "The ns-3 Network Simulator Project",
    tagline: "ns-3 is a simulation tool for computer networks.",
    skills: ["python", "django", "c++"],
    topicTags: ["computer networking", "network simulation"],
    ideasLink: "https://www.nsnam.org/wiki/GSOC2022Projects",
    websiteLink: "https://www.nsnam.org",
    categories: ["Science and medicine"],
  },

  {
    id: 56,
    name: "cBioPortal for Cancer Genomics",
    tagline: "Aid discovery in complex cancer genomics data",
    skills: ["mysql", "javascript", "java", "react", "typescript"],
    topicTags: [
      "genomics",
      "cancer",
      "bioinformatics",
      "big data",
      "precision medicine",
    ],
    ideasLink:
      "https://github.com/cBioPortal/GSoC/issues?q=is%3Aopen+is%3Aissue+label%3AGSoC-2022",
    websiteLink: "https://www.cbioportal.org/",
    categories: ["Science and medicine"],
  },
];
